#!/bin/bash
case $1 in
   config)
        cat <<'EOM'
graph_args --base 1024 -l 0
graph_title Redis Memory
graph_vlabel memory
graph_category redis
memory.label memory
memory.draw AREA
EOM
        exit 0;;
esac

redis-cli info | grep 'used_memory:' | awk -F':' '{ print "memory.value " $2 }'